name: Links checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          # All supported file formats to be verified and accept 403 (Forbidden) as correct link
          args: --verbose -a 200,202,403 './**/*.md' './**/*.html' './**/*.rst' --exclude 'https:\/\/[^/]*cp-[^/]*\.chili-publish\.online\/.*'
          # Use json as output format (instead of markdown)
          format: markdown
          jobSummary: true
          # Fail job if one or more links are failing
          fail: true

           
   