name: Links checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose -a 200,202,403 './**/*.md' './**/*.html' './**/*.rst' 
          # Use json as output format (instead of markdown)
          format: json
      - name: Link report upload
        uses: actions/upload-artifact@v3
        with:
            name: link-report
            path: ./lychee/out.md
            retention-days: 30
           
   